// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RelationShipsBetweenEmployeeAndDepartment.Data;

#nullable disable

namespace RelationShipsBetweenEmployeeAndDepartment.Data.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20251018234332_TryToAddManageAndWorkRelationship")]
    partial class TryToAddManageAndWorkRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RelationShipsBetweenEmployeeAndDepartment.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("MangerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("MangerId")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("RelationShipsBetweenEmployeeAndDepartment.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Salary")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RelationShipsBetweenEmployeeAndDepartment.Models.Department", b =>
                {
                    b.HasOne("RelationShipsBetweenEmployeeAndDepartment.Models.Employee", "Manger")
                        .WithOne("DepartmentToManage")
                        .HasForeignKey("RelationShipsBetweenEmployeeAndDepartment.Models.Department", "MangerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manger");
                });

            modelBuilder.Entity("RelationShipsBetweenEmployeeAndDepartment.Models.Employee", b =>
                {
                    b.HasOne("RelationShipsBetweenEmployeeAndDepartment.Models.Department", "WorkDepartment")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("WorkDepartment");
                });

            modelBuilder.Entity("RelationShipsBetweenEmployeeAndDepartment.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RelationShipsBetweenEmployeeAndDepartment.Models.Employee", b =>
                {
                    b.Navigation("DepartmentToManage");
                });
#pragma warning restore 612, 618
        }
    }
}
